services:
  # Backend Flask
  flask:
    build:
      context: ./backend  # Cambia el path según la ubicación de tu proyecto Flask
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    depends_on:
      - mysql

  # Frontend Angular con Nginx
  angular:
    build:
      context: ./frontend  # Cambia el path según la ubicación de tu proyecto Angular
    container_name: angular-frontend
    ports:
      - "80:80"  # Exponemos el puerto 80 de Nginx
    depends_on:
      - flask

  # Base de datos MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root # No iba porque no era la contraseña indicada
      MYSQL_DATABASE: gestionreservas # Ahora la base de datos si es la correcta
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: