services:
  frontend:
    build:
      context: ./FrontendAngular  # Usará el Dockerfile para construir la imagen con Nginx
    container_name: angular_app
    ports:
      - "80:80"  # Mapea el puerto 80 del contenedor al puerto 80 del host
    networks:
      - app_network
    depends_on:
      - python  # Si el frontend depende del backend

  python:
    image: python:3.9-slim  # Imagen base de Python para tu aplicación Flask
    container_name: python_app
    volumes:
      - ./Backend:/app  # El código de tu aplicación Flask
    working_dir: /app
    command: python app.py  # Comando para ejecutar la aplicación Flask
    ports:
      - "5000:5000"  # El backend sigue en el puerto 5000
    networks:
      - app_network
    depends_on:
      - mysql

  db:
    image: mysql:8.1.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toor
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge