services:

  python:
    build:
      context: ./Backend
    container_name: python_app
    volumes:
      - ./Backend:/app
    working_dir: /app
    command: python app.py
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mysql
    
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./Backend/nginx.conf:/etc/nginx/nginx.conf  # Usa tu archivo de configuración Nginx si tienes uno
      - ./Backend:/app
    ports:
      - "80:80"
    depends_on:
      - python
    networks:
      - app_network
  

  db:
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toor
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
    
