services:
  
  angular:
    build:
      context: ./FrontendAngular
    container_name: angular_app
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - python
  python:
    build:
      context: ./Backend
    container_name: python_app
    volumes:
      - ./Backend:/app
    working_dir: /app
    command: python app.py
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mysql:8.1.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toor
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge