services:
  
  # Servicio para la aplicación Angular
  angular:
    build:
      context: ./FrontendAngular
    container_name: angular_app
    ports:
      - "80:80"  # Expone el puerto 80
    networks:
      - app_network
    depends_on:
      - python
  python:
    build:
      context: ./Backend
    container_name: python_app
    volumes:
      - ./Backend:/app
    working_dir: /app
    command: python app.py
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mysql
    
  db:
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toor
    volumes:
      - ./mysql_data:/var/lib/mysql

  # Servicio para phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db

networks:
  app_network:
    driver: bridge